### ISSUE TITLE
Issue with passed layout in default `cholesky!_layout` method for Symmetric matrices

### ISSUE THREAD

**Issue by DanielVandH** [JuliaLinearAlgebra/ArrayLayouts.jl#244]
https://github.com/JuliaLinearAlgebra/ArrayLayouts.jl/blob/a77697d30fb4c954f05a4bb101e6c2e2f8e13a39/src/factorizations.jl#L382-L386

Should the call to `_chol!` be passing `MemoryLayout(A.data)` instead of simply `layout`? Something similar is done for `reversecholesky` here

https://github.com/JuliaLinearAlgebra/MatrixFactorizations.jl/blob/d3f30bb62fc282e9a3873a858f2823339888e143/src/reversecholesky.jl#L113-L117

which I think is more correct?

**Comment by jishnub** [comment]
I think the idea is that `layout` represents the desired memory layout that has already been computed? Does this lead to issues somewhere?

**Comment by DanielVandH** [comment]
It doesn't lead to any issues that I've seen, I only noticed it while implementing the two methods elsewhere and saw the difference, so I wasn't sure if it was intentional or not.
